# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/caesar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = '../platforms'

class Ui_QMainWindow(object):
    def setupUi(self, QMainWindow):
        QMainWindow.setObjectName("QMainWindow")
        QMainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(QMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.CaesarCipher_lbl = QtWidgets.QLabel(self.centralwidget)
        self.CaesarCipher_lbl.setGeometry(QtCore.QRect(290, 40, 171, 41))
        self.CaesarCipher_lbl.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.CaesarCipher_lbl.setFont(font)
        self.CaesarCipher_lbl.setObjectName("CaesarCipher_lbl")
        self.PlainText_lbl = QtWidgets.QLabel(self.centralwidget)
        self.PlainText_lbl.setGeometry(QtCore.QRect(50, 130, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PlainText_lbl.setFont(font)
        self.PlainText_lbl.setObjectName("PlainText_lbl")
        self.txt_cipher_text = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_cipher_text.setGeometry(QtCore.QRect(140, 330, 481, 151))
        self.txt_cipher_text.setObjectName("txt_cipher_text")
        self.Key_lbl = QtWidgets.QLabel(self.centralwidget)
        self.Key_lbl.setGeometry(QtCore.QRect(50, 280, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Key_lbl.setFont(font)
        self.Key_lbl.setObjectName("Key_lbl")
        self.txt_key = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_key.setGeometry(QtCore.QRect(140, 280, 481, 31))
        self.txt_key.setObjectName("txt_key")
        self.CipherText_lbl = QtWidgets.QLabel(self.centralwidget)
        self.CipherText_lbl.setGeometry(QtCore.QRect(50, 330, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CipherText_lbl.setFont(font)
        self.CipherText_lbl.setObjectName("CipherText_lbl")
        self.btn_encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_encrypt.setGeometry(QtCore.QRect(200, 510, 75, 23))
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.btn_decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_decrypt.setGeometry(QtCore.QRect(500, 510, 75, 23))
        self.btn_decrypt.setObjectName("btn_decrypt")
        self.txt_plain_text = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_plain_text.setGeometry(QtCore.QRect(140, 130, 481, 131))
        self.txt_plain_text.setObjectName("txt_plain_text")
        QMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(QMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        QMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(QMainWindow)
        self.statusbar.setObjectName("statusbar")
        QMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(QMainWindow)
        QtCore.QMetaObject.connectSlotsByName(QMainWindow)

    def retranslateUi(self, QMainWindow):
        _translate = QtCore.QCoreApplication.translate
        QMainWindow.setWindowTitle(_translate("QMainWindow", "MainWindow"))
        self.CaesarCipher_lbl.setText(_translate("QMainWindow", "Caesar Cipher"))
        self.PlainText_lbl.setText(_translate("QMainWindow", "Plain text:"))
        self.Key_lbl.setText(_translate("QMainWindow", "Key:"))
        self.CipherText_lbl.setText(_translate("QMainWindow", "Cipher text:"))
        self.btn_encrypt.setText(_translate("QMainWindow", "Encrypt"))
        self.btn_decrypt.setText(_translate("QMainWindow", "Decrypt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    QMainWindow = QtWidgets.QMainWindow()
    ui = Ui_QMainWindow()
    ui.setupUi(QMainWindow)
    QMainWindow.show()
    sys.exit(app.exec_())
