# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/ecc.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = '../platforms'

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_sign = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sign.setGeometry(QtCore.QRect(230, 480, 75, 23))
        self.btn_sign.setObjectName("btn_sign")
        self.information_lbl = QtWidgets.QLabel(self.centralwidget)
        self.information_lbl.setGeometry(QtCore.QRect(80, 130, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.information_lbl.setFont(font)
        self.information_lbl.setObjectName("information_lbl")
        self.CaesarCipher_lbl = QtWidgets.QLabel(self.centralwidget)
        self.CaesarCipher_lbl.setGeometry(QtCore.QRect(320, 40, 171, 41))
        self.CaesarCipher_lbl.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.CaesarCipher_lbl.setFont(font)
        self.CaesarCipher_lbl.setObjectName("CaesarCipher_lbl")
        self.btn_verify = QtWidgets.QPushButton(self.centralwidget)
        self.btn_verify.setGeometry(QtCore.QRect(530, 480, 75, 23))
        self.btn_verify.setObjectName("btn_verify")
        self.txt_sign = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_sign.setGeometry(QtCore.QRect(170, 300, 481, 151))
        self.txt_sign.setObjectName("txt_sign")
        self.signature_lbl = QtWidgets.QLabel(self.centralwidget)
        self.signature_lbl.setGeometry(QtCore.QRect(80, 300, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.signature_lbl.setFont(font)
        self.signature_lbl.setObjectName("signature_lbl")
        self.txt_info = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_info.setGeometry(QtCore.QRect(170, 130, 481, 131))
        self.txt_info.setObjectName("txt_info")
        self.btn_gen_keys = QtWidgets.QPushButton(self.centralwidget)
        self.btn_gen_keys.setGeometry(QtCore.QRect(530, 50, 75, 23))
        self.btn_gen_keys.setObjectName("btn_gen_keys")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_sign.setText(_translate("MainWindow", "Sign"))
        self.information_lbl.setText(_translate("MainWindow", "Information:"))
        self.CaesarCipher_lbl.setText(_translate("MainWindow", "ECC Cipher"))
        self.btn_verify.setText(_translate("MainWindow", "Verify"))
        self.signature_lbl.setText(_translate("MainWindow", "Signature:"))
        self.btn_gen_keys.setText(_translate("MainWindow", "Generate Key"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
