# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = '../platforms'

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1168, 585)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_sign = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sign.setGeometry(QtCore.QRect(780, 460, 75, 23))
        self.btn_sign.setObjectName("btn_sign")
        self.signature_lbl = QtWidgets.QLabel(self.centralwidget)
        self.signature_lbl.setGeometry(QtCore.QRect(630, 280, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.signature_lbl.setFont(font)
        self.signature_lbl.setObjectName("signature_lbl")
        self.txt_info = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_info.setGeometry(QtCore.QRect(720, 110, 481, 131))
        self.txt_info.setObjectName("txt_info")
        self.btn_verify = QtWidgets.QPushButton(self.centralwidget)
        self.btn_verify.setGeometry(QtCore.QRect(1080, 460, 75, 23))
        self.btn_verify.setObjectName("btn_verify")
        self.btn_gen_keys = QtWidgets.QPushButton(self.centralwidget)
        self.btn_gen_keys.setGeometry(QtCore.QRect(720, 30, 75, 23))
        self.btn_gen_keys.setObjectName("btn_gen_keys")
        self.txt_sign = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_sign.setGeometry(QtCore.QRect(720, 280, 481, 151))
        self.txt_sign.setObjectName("txt_sign")
        self.information_lbl = QtWidgets.QLabel(self.centralwidget)
        self.information_lbl.setGeometry(QtCore.QRect(630, 110, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.information_lbl.setFont(font)
        self.information_lbl.setObjectName("information_lbl")
        self.btn_decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_decrypt.setGeometry(QtCore.QRect(450, 460, 75, 23))
        self.btn_decrypt.setObjectName("btn_decrypt")
        self.btn_encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_encrypt.setGeometry(QtCore.QRect(150, 460, 75, 23))
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.PlainText_lbl = QtWidgets.QLabel(self.centralwidget)
        self.PlainText_lbl.setGeometry(QtCore.QRect(10, 110, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PlainText_lbl.setFont(font)
        self.PlainText_lbl.setObjectName("PlainText_lbl")
        self.CipherText_lbl = QtWidgets.QLabel(self.centralwidget)
        self.CipherText_lbl.setGeometry(QtCore.QRect(10, 280, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CipherText_lbl.setFont(font)
        self.CipherText_lbl.setObjectName("CipherText_lbl")
        self.txt_plain_text = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_plain_text.setGeometry(QtCore.QRect(90, 110, 481, 131))
        self.txt_plain_text.setObjectName("txt_plain_text")
        self.txt_cipher_text = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_cipher_text.setGeometry(QtCore.QRect(90, 280, 481, 151))
        self.txt_cipher_text.setObjectName("txt_cipher_text")
        self.RSACipher_lbl = QtWidgets.QLabel(self.centralwidget)
        self.RSACipher_lbl.setGeometry(QtCore.QRect(530, 20, 171, 41))
        self.RSACipher_lbl.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.RSACipher_lbl.setFont(font)
        self.RSACipher_lbl.setObjectName("RSACipher_lbl")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1168, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_sign.setText(_translate("MainWindow", "Sign"))
        self.signature_lbl.setText(_translate("MainWindow", "Signature:"))
        self.btn_verify.setText(_translate("MainWindow", "Verify"))
        self.btn_gen_keys.setText(_translate("MainWindow", "Generate Key"))
        self.information_lbl.setText(_translate("MainWindow", "Information:"))
        self.btn_decrypt.setText(_translate("MainWindow", "Decrypt"))
        self.btn_encrypt.setText(_translate("MainWindow", "Encrypt"))
        self.PlainText_lbl.setText(_translate("MainWindow", "Plain text:"))
        self.CipherText_lbl.setText(_translate("MainWindow", "Cipher text:"))
        self.RSACipher_lbl.setText(_translate("MainWindow", "RSA Cipher"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
